- dist/amd/rest.js
- dist/commonjs/rest.js
- dist/es6/rest.js
- dist/system/rest.js
- doc/CHANGELOG.md
- package.json
- src/rest.js
Passing in null still caused the rest client to set a body
> undefined body

- doc/getting-started.md
doc(getting-started): Fixed wrong variable
> doc(getting-started): Fixed wrong variable

- dist/amd/config.js
- dist/commonjs/config.js
- dist/es6/config.js
- dist/system/config.js
- doc/CHANGELOG.md
- package.json
- src/config.js
fix(config): Be more permissive when looking for the default endpoint
> fix(config): Be more permissive when looking for the default endpoint

- build/tasks/server.js
- dist/amd/rest.js
- dist/commonjs/rest.js
- dist/es6/rest.js
- dist/system/rest.js
- doc/CHANGELOG.md
- package.json
- src/rest.js
- test/rest.spec.js
as required by current aurelia-auth
updateMe(body, criteria) {
if (typeof criteria === 'string' || typeof criteria === 'number') {
criteria = {id: criteria};
}
return this.client.update(this.auth.getProfileUrl(), criteria, body);
}
> Feat criteria

- .travis.yml
- package.json
> Added semantic-release

- .travis.yml
- package.json
> chore(project): Revert semantic-release update

- README.md
- dist/amd/aurelia-api.d.ts
- dist/amd/aurelia-api.js
- dist/aurelia-api.d.ts
- dist/aurelia-api.js
- dist/commonjs/aurelia-api.d.ts
- dist/commonjs/aurelia-api.js
- dist/es2015/aurelia-api.d.ts
- dist/es2015/aurelia-api.js
- dist/system/aurelia-api.d.ts
- dist/system/aurelia-api.js
- doc/CHANGELOG.md
- package.json
- src/config.js
- src/rest.js
- test/aurelia-api.spec.js
- test/config.spec.js
- test/endpoint.spec.js
- test/rest.spec.js
@RWOverdijk please review
'preview'. made for babel6 update
> fix(config): apply user endpoint defaults

- build/args.js
- build/babel-options.js
- build/paths.js
- build/tasks/dev.js
- build/tasks/lint.js
- build/tasks/test.js
* linted tasks
* updated dev tasks
> chore(build): add lint-test task

- doc/rest.md
- src/config.js
- src/rest.js
makes life easier if Rest knows which endpoint it is for
> feat(Rest): add property 'endpoint'

- README.md
doc(readme): Added gitter badge
> doc(readme): Added gitter badge

- dist/amd/aurelia-api.d.ts
- dist/commonjs/aurelia-api.d.ts
- dist/es2015/aurelia-api.d.ts
- dist/system/aurelia-api.d.ts
used coming babel-dts-generator to mark all unknown function parameter types as optional
> fix(typings): mark optional parameters

- config.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/103)
> chore(project): dep update

- book.json
- doc/Quick start.md
- doc/README.md
- doc/SUMMARY.md
- doc/api_rest.md
- doc/configuration.md
- doc/license.md
- doc/usage.md
doc(project): Moved book to project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/106)
> doc(project): Moved book to project

- src/endpoint.js
- src/rest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/107)
> Fix content type

- src/config.js
- src/endpoint.js
- src/rest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/108)
> doc(project): TS lint doc blocks

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/112)
> doc(readme): copied forks instructions from authentication

- package.json
https://greenkeeper.io/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/117)
> chore(package): update karma-coverage to version 1.0.0

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/119)
> Greenkeeper

- package.json
https://greenkeeper.io/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/120)
> chore(package): update babel-eslint to version 6.0.4

- config.js
- package.json
- src/rest.js
- test/rest.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/116)
> refactor(rest): use aurelia-path instead of qs

- bower.json
- package.json
- test/endpoint.spec.js
- test/resources/inject-test.js
- test/rest.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/113)
> chore(project): add bower.json

- README.md
- doc/installation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/136)
> doc(all): fix extend type and move doc up where needed

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/137)
> chore(project): lower dependencies

- README.md
- doc/installation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/144)
> doc(installation): typo and clarification

- bower.json
- dist/amd/aurelia-api.js
- dist/amd/index.js
- dist/aurelia-api.js
- dist/commonjs/aurelia-api.js
- dist/commonjs/index.js
- dist/es2015/aurelia-api.js
- dist/native-modules/aurelia-api.js
- dist/system/aurelia-api.js
- dist/system/index.js
- doc/CHANGELOG.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/147)
> Build bump rc7

- bower.json
- dist/amd/aurelia-api.js
- dist/aurelia-api.js
- dist/commonjs/aurelia-api.js
- dist/es2015/aurelia-api.js
- dist/native-modules/aurelia-api.js
- dist/system/aurelia-api.js
- doc/CHANGELOG.md
- package.json
- src/rest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/148)
> Build bump rc8

- src/rest.js
- test/rest.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/156)
> fix(rest): convert number to string before joining path

- doc/configuration.md
- src/aurelia-api.js
- src/config.js
- test/config.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/165)
> feat(configure): allow configuration with an object

- src/rest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/164)
> fix(rest) enable charset

- src/rest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/172)
> Yutackall content type charset

- README.md
- bower.json
- config.js
- dist/amd/aurelia-api.js
- dist/aurelia-api.d.ts
- dist/aurelia-api.js
- dist/commonjs/aurelia-api.js
- dist/es2015/aurelia-api.js
- dist/native-modules/aurelia-api.js
- dist/system/aurelia-api.js
- doc/CHANGELOG.md
- doc/README.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/173)
> Release 3.0.0

- gulpfile.js
- package.json
- spoonx.js
pending https://github.com/SpoonX/spoonx-tools/pull/13
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/177)
> chore(project): add npm version scripts

- README.md
- doc/README.md
- doc/api_rest.md
- src/rest.js
resolves #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/183)
> chore(rest): renamed criteria to idOrCriteria for clarity

- src/config.js
- src/endpoint.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/205)
> refactor(types): mark endpoint key as optional

- README.md
- doc/Quick start.md
- doc/README.md
- src/endpoint.js
- src/rest.js
- test/rest.spec.js
Closes #198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/199)
> feat(rest): add responseOutput to expose response object from fetch call

- test/resources/inject-test.js
- test/rest.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/214)
> chore(test): added test for applying registered default headers

- bower.json
- dist/amd/aurelia-api.js
- dist/aurelia-api.d.ts
- dist/aurelia-api.js
- dist/commonjs/aurelia-api.js
- dist/es2015/aurelia-api.js
- dist/native-modules/aurelia-api.js
- dist/system/aurelia-api.js
- doc/CHANGELOG.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spoonx/aurelia-api/216)
> chore(*): bump 3.2.0
